[package]
name = "egui-tokio-example"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.19"
reqwest = { version = "0.11", features = ["json"] }
serde = "1"
serde_derive = "1"
tokio = { version = "1", features = ["net", "rt-multi-thread"] }
